### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by 24fw** [COVERTIV/Liberty-skin#11]
![IMG_0206](https://github.com/COVERTIV/Liberty-skin/assets/100505515/68391edb-86fa-471c-92e5-ea4e4fe64a38)

스레드창이 화면을 넘어감

**Comment by theseeduser** [comment]
이 업데이트는 테스트위키에만 단독 적용되었습니다.
[[https://testwiki.xyz/thread/FoamyRedNoisyKey|관련 토론]]
현재 모바일 환경 버그가 있는 것을 알고 있습니다. 그래서 수정해보려고 합니다.

**Comment by theseeduser** [comment]
정식으로 업데이트 될 때까지는 되돌려 놓겠습니다
