### ISSUE TITLE
공지 내린 후 공지 부분이 여백으로 남아있는 오류

### ISSUE THREAD

**Issue by theseeduser** [COVERTIV/Liberty-skin#12]

**Comment by Roselia31** [comment]
아마도 vue 기능을 html로 구현한거다 보니 한계가 있는 뜻합니다. 그래서 더시드 리버티보다는 미디어위키 리버티 처럼 수정하겠습니다.

**Comment by Roselia31** [comment]
어려 오류로 실패 다시 원래되로 복구
ecaf0f1a5d7beedb5904de85265b6f3152c491a6
