### ISSUE TITLE
기능 추가 제안합니다.

### ISSUE THREAD

**Issue by theseeduser** [COVERTIV/Liberty-skin#3]
- [x] 별찜 버튼 추가
- [x] 제목 클릭했을 때 해당 문서로 이동 기능 구현 후 문서 버튼 삭제
- [기각] 문서를 읽을 때에는 이동, 삭제 버튼이 보이지 않게 변경
- [기각] 문서 편집 시 역링크, 삭제 (빨간색 배경), 이동 버튼만 보이게 수정

**Comment by roselia2023** [comment]
1. 검토하겠습니다
2. 개편하며 신형 더시드 리버티 처럼 빼버릴 예정입니다.
3. 추가할 예정입니다
4. 추가할 예정입니다

**Comment by roselia2023** [comment]
문서를 읽을 때에는 이동, 삭제 버튼이 보이지 않게 변경 이거는 도저히 작업이 불가능하여 기각 처리하였습니다.

**Comment by roselia2023** [comment]
문서 편집 시 역링크, 삭제 (빨간색 배경), 이동 버튼만 보이게 수정는 지금은 딱히 불편함을 모르겠어서 기각 처리합니다. 다음에 기회되면 작업하겠습니다.

**Comment by roselia2023** [comment]
다른 것들은 작업 완료

**Comment by roselia2023** [comment]
Star 기능은 아직 개발자의 코딩 실력 부족으로 완벽하지는 않습니다. 그래서 별을 해체 할려면 도메인에 star 앞에 un을 붙혀서 
wiki.wiki/member/unstar/문서명 으로 해야 해체됩니다. 이건 추후 고치겠습니다.

**Comment by theseeduser** [comment]
코드에 수정된 버전이 없네요

**Comment by roselia2023** [comment]
#[1.4](https://github.com/COVERTIV/Liberty-skin/commit/3f938b2c68f4ca25db5e6c2655164aa9b212825b)
#[1.4](https://github.com/COVERTIV/Liberty-skin/commit/c028ae77b5e140d45ff8a88d51fa655b17143f94)
