### ISSUE TITLE
수정 요청

### ISSUE THREAD

**Issue by theseeduser** [COVERTIV/Liberty-skin#4]
- [ ] 모바일 환경에서 오른쪽으로 스크롤 할 때 잘린 내용이 표시되지 않아서 긴 이름을 가진 ACL 삭제가 불가능합니다.

- [x]  최신 더 시드 리버티와 같은 문구 (임의문서->임의 문서, 최근바뀜->최근 변경, 더보기->더 보기, 업로드->파일 올리기, 검색 아이콘을 왼쪽으로 이동하고 눈 아이콘을 오른쪽 화살표로 수정 및 오른쪽으로 이동)으로 수정 부탁드립니다.

- 자동 다크모드 전환 지원

(추가) 스레드 디자인을 현재 the seed 사용 위키에서 사용중인 디자인으로 변경

**Comment by Roselia31** [comment]
1. 작업하도록 하겠습니다.
2. 작업하도록 하겠습니다.
3. 해당 기능은 엔진 관련으로 판단됩니다. 기각합니다.

**Comment by Roselia31** [comment]
472e4a43b9c78b90f857adca686ca08a2d8d5739

**Comment by Roselia31** [comment]
2번
v1.8 472e4a43b9c78b90f857adca686ca08a2d8d5739

**Comment by theseeduser** [comment]
layout.html 106줄에 아직 최근바뀜으로 되어있습니다

**Comment by Roselia31** [comment]
> layout.html 106줄에 아직 최근바뀜으로 되어있습니다
a98b729a2291ccd50fac843cc97ff45221d56788 
수정 하였어요

**Comment by Roselia31** [comment]
일단 결론적으로 **모바일 환경에서 오른쪽으로 스크롤 할 때 잘린 내용이 표시되지 않아서 긴 이름을 가진 ACL 삭제가 불가능합니다.** 이 문제는 좀 많이 시간이 걸릴 거 같습니다. buma 참고한 결과 css에서 추가해야 하는 문제인데 css 자체에서 어떻게 구현해야 할지는 알지만 리버티 css는 기본적으로 class가 css 이름되로 안 잡혀있습니다. 그래서 찾는 시간도 필요한데 이게 좀 오래 걸릴 듯 싶습니다.

**Comment by Roselia31** [comment]
엔진에서 처리해야 할 문제로 판단됨.
