### ISSUE TITLE
수정 요청

### ISSUE THREAD

**Issue by theseeduser** [COVERTIV/Liberty-skin#6]
1. 없는 문서에 역링크, 토론, 편집, 역사, ACL 버튼 보이게 변경
2. 최근 토론에서 오래된 편집 요청 버튼 추가

항상 수고 많으십니다.

**Comment by Roselia31** [comment]
1. 고려보겠으나 vue 기능일 확률이 큽니다.
2. 해당 기능은 엔진 기능입니다.

**Comment by Roselia31** [comment]
v 1.14 e1b6fa7b20975cf9c4fe475d35a405c457b9e731
