### ISSUE TITLE
[공지] 업데이트 예정 노트

### ISSUE THREAD

**Issue by Roselia31** [COVERTIV/Liberty-skin#8]
- [ ] 스레드에서 글자가 밑으로 간 버그 수정
- [ ] 다크모드

다크모드는 구성이 어떻게 되어 있는지 senkawa 참고할건데 다크모드가 될지는 모르겠음.

**Comment by theseeduser** [comment]
모바일에서는 다크모드 됩니다. PC는 시도 안해봐서 모르겠네요.
